name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Backend CI/CD", "Frontend CI/CD"] 
    types:
      - completed
concurrency:
  group: deploy-to-ec2
  cancel-in-progress: true
jobs:
  deploy:
    # Chỉ chạy nếu workflow trước đó THÀNH CÔNG
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker compose pull
            docker compose down
            docker compose up -d